use_frameworks!

platform :ios, '11.0'

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
#            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
         end
    end
  end
end


target 'TTBusinessComponents_Example' do
  pod 'TTBusinessComponents', :path => '../'
  pod 'TTUIKit',:path => '../../TTUIKit'
  pod 'TTAssistKit',:path => '../../TTAssistKit'
  pod 'IQKeyboardManagerSwift'
  pod 'LookinServer', :configurations => ['Debug']#DEBug调试UI用,得配合Lookin客户端
  target 'TTBusinessComponents_Tests' do
    inherit! :search_paths
  end
end
